dnl -*- mode: autoconf -*-

# serial 1

dnl Usage:
dnl   GCREATE_CLASS_INIT([Description][COPYRIGHT])
AC_DEFUN([GCREATE_CLASS_INIT],
[
  AC_PATH_PROG(PERL, perl)
  GCREATE_CLASS_DESCRIPTION="$1"
  AC_SUBST([GCREATE_CLASS_DESCRIPTION])
  GCREATE_CLASS_COPYRIGHT="$2"
  AC_SUBST([GCREATE_CLASS_COPYRIGHT])
])
