/*
 * This file is part of Gibbon, a graphical frontend to the First Internet 
 * Backgammon Server FIBS.
 * Copyright (C) 2009-2011 Guido Flohr, http://guido-flohr.net/.
 *
 * Gibbon is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Gibbon is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Gibbon.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file is generated, do not edit! Edit `isolist.txt' in the same
 * directory instead!
 */

#ifndef _GIBBON_COUNTRIES_H
#define _GIBBON_COUNTRIES_H

enum GibbonCountry {
        GIBBON_COUNTRY_af = 4,
        GIBBON_COUNTRY_al = 8,
        GIBBON_COUNTRY_aq = 10,
        GIBBON_COUNTRY_dz = 12,
        GIBBON_COUNTRY_as = 16,
        GIBBON_COUNTRY_ad = 20,
        GIBBON_COUNTRY_ao = 24,
        GIBBON_COUNTRY_ag = 28,
        GIBBON_COUNTRY_az = 31,
        GIBBON_COUNTRY_ar = 32,
        GIBBON_COUNTRY_au = 36,
        GIBBON_COUNTRY_at = 40,
        GIBBON_COUNTRY_bs = 44,
        GIBBON_COUNTRY_bh = 48,
        GIBBON_COUNTRY_bd = 50,
        GIBBON_COUNTRY_am = 51,
        GIBBON_COUNTRY_bb = 52,
        GIBBON_COUNTRY_be = 56,
        GIBBON_COUNTRY_bm = 60,
        GIBBON_COUNTRY_bt = 64,
        GIBBON_COUNTRY_bo = 68,
        GIBBON_COUNTRY_ba = 70,
        GIBBON_COUNTRY_bw = 72,
        GIBBON_COUNTRY_bv = 74,
        GIBBON_COUNTRY_br = 76,
        GIBBON_COUNTRY_bz = 84,
        GIBBON_COUNTRY_io = 86,
        GIBBON_COUNTRY_sb = 90,
        GIBBON_COUNTRY_vg = 92,
        GIBBON_COUNTRY_bn = 96,
        GIBBON_COUNTRY_bg = 100,
        GIBBON_COUNTRY_mm = 104,
        GIBBON_COUNTRY_bi = 108,
        GIBBON_COUNTRY_by = 112,
        GIBBON_COUNTRY_kh = 116,
        GIBBON_COUNTRY_cm = 120,
        GIBBON_COUNTRY_ca = 124,
        GIBBON_COUNTRY_cv = 132,
        GIBBON_COUNTRY_ky = 136,
        GIBBON_COUNTRY_cf = 140,
        GIBBON_COUNTRY_lk = 144,
        GIBBON_COUNTRY_td = 148,
        GIBBON_COUNTRY_cl = 152,
        GIBBON_COUNTRY_cn = 156,
        GIBBON_COUNTRY_tw = 158,
        GIBBON_COUNTRY_cx = 162,
        GIBBON_COUNTRY_cc = 166,
        GIBBON_COUNTRY_co = 170,
        GIBBON_COUNTRY_km = 174,
        GIBBON_COUNTRY_yt = 175,
        GIBBON_COUNTRY_cg = 178,
        GIBBON_COUNTRY_zr = 180,
        GIBBON_COUNTRY_ck = 184,
        GIBBON_COUNTRY_cr = 188,
        GIBBON_COUNTRY_hr = 191,
        GIBBON_COUNTRY_cu = 192,
        GIBBON_COUNTRY_cy = 196,
        GIBBON_COUNTRY_cz = 203,
        GIBBON_COUNTRY_bj = 204,
        GIBBON_COUNTRY_dk = 208,
        GIBBON_COUNTRY_dm = 212,
        GIBBON_COUNTRY_do = 214,
        GIBBON_COUNTRY_ec = 218,
        GIBBON_COUNTRY_sv = 222,
        GIBBON_COUNTRY_gq = 226,
        GIBBON_COUNTRY_et = 231,
        GIBBON_COUNTRY_er = 232,
        GIBBON_COUNTRY_ee = 233,
        GIBBON_COUNTRY_fo = 234,
        GIBBON_COUNTRY_fk = 238,
        GIBBON_COUNTRY_gs = 239,
        GIBBON_COUNTRY_fj = 242,
        GIBBON_COUNTRY_fi = 246,
        GIBBON_COUNTRY_fx = 249,
        GIBBON_COUNTRY_fr = 250,
        GIBBON_COUNTRY_gf = 254,
        GIBBON_COUNTRY_pf = 258,
        GIBBON_COUNTRY_tf = 260,
        GIBBON_COUNTRY_dj = 262,
        GIBBON_COUNTRY_ga = 266,
        GIBBON_COUNTRY_ge = 268,
        GIBBON_COUNTRY_gm = 270,
        GIBBON_COUNTRY_de = 276,
        GIBBON_COUNTRY_gh = 288,
        GIBBON_COUNTRY_gi = 292,
        GIBBON_COUNTRY_ki = 296,
        GIBBON_COUNTRY_gr = 300,
        GIBBON_COUNTRY_gl = 304,
        GIBBON_COUNTRY_gd = 308,
        GIBBON_COUNTRY_gp = 312,
        GIBBON_COUNTRY_gu = 316,
        GIBBON_COUNTRY_gt = 320,
        GIBBON_COUNTRY_gn = 324,
        GIBBON_COUNTRY_gy = 328,
        GIBBON_COUNTRY_ht = 332,
        GIBBON_COUNTRY_hm = 334,
        GIBBON_COUNTRY_va = 336,
        GIBBON_COUNTRY_hn = 340,
        GIBBON_COUNTRY_hk = 344,
        GIBBON_COUNTRY_hu = 348,
        GIBBON_COUNTRY_is = 352,
        GIBBON_COUNTRY_in = 356,
        GIBBON_COUNTRY_id = 360,
        GIBBON_COUNTRY_ir = 364,
        GIBBON_COUNTRY_iq = 368,
        GIBBON_COUNTRY_ie = 372,
        GIBBON_COUNTRY_il = 376,
        GIBBON_COUNTRY_it = 380,
        GIBBON_COUNTRY_ci = 384,
        GIBBON_COUNTRY_jm = 388,
        GIBBON_COUNTRY_jp = 392,
        GIBBON_COUNTRY_kz = 398,
        GIBBON_COUNTRY_jo = 400,
        GIBBON_COUNTRY_ke = 404,
        GIBBON_COUNTRY_kp = 408,
        GIBBON_COUNTRY_kr = 410,
        GIBBON_COUNTRY_kw = 414,
        GIBBON_COUNTRY_kg = 417,
        GIBBON_COUNTRY_la = 418,
        GIBBON_COUNTRY_lb = 422,
        GIBBON_COUNTRY_ls = 426,
        GIBBON_COUNTRY_lv = 428,
        GIBBON_COUNTRY_lr = 430,
        GIBBON_COUNTRY_ly = 434,
        GIBBON_COUNTRY_li = 438,
        GIBBON_COUNTRY_lt = 440,
        GIBBON_COUNTRY_lu = 442,
        GIBBON_COUNTRY_mo = 446,
        GIBBON_COUNTRY_mg = 450,
        GIBBON_COUNTRY_mw = 454,
        GIBBON_COUNTRY_my = 458,
        GIBBON_COUNTRY_mv = 462,
        GIBBON_COUNTRY_ml = 466,
        GIBBON_COUNTRY_mt = 470,
        GIBBON_COUNTRY_mq = 474,
        GIBBON_COUNTRY_mr = 478,
        GIBBON_COUNTRY_mu = 480,
        GIBBON_COUNTRY_mx = 484,
        GIBBON_COUNTRY_mc = 492,
        GIBBON_COUNTRY_mn = 496,
        GIBBON_COUNTRY_md = 498,
        GIBBON_COUNTRY_ms = 500,
        GIBBON_COUNTRY_ma = 504,
        GIBBON_COUNTRY_mz = 508,
        GIBBON_COUNTRY_om = 512,
        GIBBON_COUNTRY_na = 516,
        GIBBON_COUNTRY_nr = 520,
        GIBBON_COUNTRY_np = 524,
        GIBBON_COUNTRY_nl = 528,
        GIBBON_COUNTRY_an = 530,
        GIBBON_COUNTRY_aw = 533,
        GIBBON_COUNTRY_nc = 540,
        GIBBON_COUNTRY_vu = 548,
        GIBBON_COUNTRY_nz = 554,
        GIBBON_COUNTRY_ni = 558,
        GIBBON_COUNTRY_ne = 562,
        GIBBON_COUNTRY_ng = 566,
        GIBBON_COUNTRY_nu = 570,
        GIBBON_COUNTRY_nf = 574,
        GIBBON_COUNTRY_no = 578,
        GIBBON_COUNTRY_mp = 580,
        GIBBON_COUNTRY_um = 581,
        GIBBON_COUNTRY_fm = 583,
        GIBBON_COUNTRY_mh = 584,
        GIBBON_COUNTRY_pw = 585,
        GIBBON_COUNTRY_pk = 586,
        GIBBON_COUNTRY_pa = 591,
        GIBBON_COUNTRY_pg = 598,
        GIBBON_COUNTRY_py = 600,
        GIBBON_COUNTRY_pe = 604,
        GIBBON_COUNTRY_ph = 608,
        GIBBON_COUNTRY_pn = 612,
        GIBBON_COUNTRY_pl = 616,
        GIBBON_COUNTRY_pt = 620,
        GIBBON_COUNTRY_gw = 624,
        GIBBON_COUNTRY_tp = 626,
        GIBBON_COUNTRY_pr = 630,
        GIBBON_COUNTRY_qa = 634,
        GIBBON_COUNTRY_re = 638,
        GIBBON_COUNTRY_ro = 642,
        GIBBON_COUNTRY_ru = 643,
        GIBBON_COUNTRY_rw = 646,
        GIBBON_COUNTRY_sh = 654,
        GIBBON_COUNTRY_kn = 659,
        GIBBON_COUNTRY_ai = 660,
        GIBBON_COUNTRY_lc = 662,
        GIBBON_COUNTRY_pm = 666,
        GIBBON_COUNTRY_vc = 670,
        GIBBON_COUNTRY_sm = 674,
        GIBBON_COUNTRY_st = 678,
        GIBBON_COUNTRY_sa = 682,
        GIBBON_COUNTRY_sn = 686,
        GIBBON_COUNTRY_sc = 690,
        GIBBON_COUNTRY_sl = 694,
        GIBBON_COUNTRY_sg = 702,
        GIBBON_COUNTRY_sk = 703,
        GIBBON_COUNTRY_vn = 704,
        GIBBON_COUNTRY_si = 705,
        GIBBON_COUNTRY_so = 706,
        GIBBON_COUNTRY_za = 710,
        GIBBON_COUNTRY_zw = 716,
        GIBBON_COUNTRY_es = 724,
        GIBBON_COUNTRY_eh = 732,
        GIBBON_COUNTRY_sd = 736,
        GIBBON_COUNTRY_sr = 740,
        GIBBON_COUNTRY_sj = 744,
        GIBBON_COUNTRY_sz = 748,
        GIBBON_COUNTRY_se = 752,
        GIBBON_COUNTRY_ch = 756,
        GIBBON_COUNTRY_sy = 760,
        GIBBON_COUNTRY_tj = 762,
        GIBBON_COUNTRY_th = 764,
        GIBBON_COUNTRY_tg = 768,
        GIBBON_COUNTRY_tk = 772,
        GIBBON_COUNTRY_to = 776,
        GIBBON_COUNTRY_tt = 780,
        GIBBON_COUNTRY_ae = 784,
        GIBBON_COUNTRY_tn = 788,
        GIBBON_COUNTRY_tr = 792,
        GIBBON_COUNTRY_tm = 795,
        GIBBON_COUNTRY_tc = 796,
        GIBBON_COUNTRY_tv = 798,
        GIBBON_COUNTRY_ug = 800,
        GIBBON_COUNTRY_ua = 804,
        GIBBON_COUNTRY_mk = 807,
        GIBBON_COUNTRY_eg = 818,
        GIBBON_COUNTRY_uk = 826,
        GIBBON_COUNTRY_tz = 834,
        GIBBON_COUNTRY_us = 840,
        GIBBON_COUNTRY_vi = 850,
        GIBBON_COUNTRY_bf = 854,
        GIBBON_COUNTRY_uy = 858,
        GIBBON_COUNTRY_uz = 860,
        GIBBON_COUNTRY_ve = 862,
        GIBBON_COUNTRY_wf = 876,
        GIBBON_COUNTRY_ws = 882,
        GIBBON_COUNTRY_ye = 887,
        GIBBON_COUNTRY_yu = 891,
        GIBBON_COUNTRY_zm = 894,
        GIBBON_COUNTRY_N_COUNTRIES
};

#endif
